env:
  - TERM=dumb
sudo: false
language: groovy
jdk:
- oraclejdk8
- openjdk8
cache:
  directories:
  - "$HOME/.gradle/caches/"
install: true
script: bash gradlew clean build
after_success: bash ./gradlew jacocoTestReport coveralls
after_failure: bash ./gradlew clean check --debug
